AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  apiKey:
    Type: String

  websiteUrl:
    Type: String
    Default: 'https://aws.amazon.com'

Resources:
  MyWebsiteMonitor:
    Type: Example::Monitoring::Website
    Properties:
      ApiKey: !Ref apiKey
      Name: 'MyWebsiteMonitor'
      Uri: !Ref websiteUrl
      Frequency: 5

Outputs:
  MonitoringKind:
    Value: !GetAtt MyWebsiteMonitor.Kind
